[icons]
name = "awesome5"
[icons.overrides]
memory_mem = ""
cpu = ""

[theme]
name = "circuit"

[[block]]
block = "custom"
command = "$HOME/.config/i3status-rust/scripts/title.sh"
hide_when_empty = true
interval = 1

[[block]]
block = "music"
player = "spotify"
buttons = ["play"]
max_width = 40
on_collapsed_click = "spotify"

[[block]]
block = "net"
device = "enp4s0"
format = ""
format_alt = "{speed_up;K} {speed_down;K}"
interval = 3

[[block]]
block = "memory"
format_mem = "{mem_used_percents:1}"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
collapsed = false
format = "{max}"
idle = 60
info = 70
warning = 80

[[block]]
block = "pacman"
format = "{pacman} |{aur}"
aur_command = "yay -Qua"

[[block]]
block = "custom"
command = "echo  $($HOME/.config/i3status-rust/scripts/trash.sh)"
interval = 10

#[[block]]
#block = "custom"
#cycle = ["echo  OFF", "echo  ON"]
#on_click = "$HOME/.config/i3status-rust/scripts/modes.sh"
#interval = "once"

[[block]]
block = "xrandr"
format = "{brightness}"
interval = 6000  # Causes lag every update

[[block]]
block = "sound"

[[block]]
block = "time"

[[block]]
block = "custom"
command = "$HOME/.config/i3status-rust/scripts/network.sh"
interval = 30

[[block]]
block = "custom"
command = "echo "
interval = "once"
on_click = "$HOME/.config/i3status-rust/scripts/power-menu.sh"
