idle_bg = "#ffffff"
idle_fg = "#67809a"
info_bg = "#5e81ac"
info_fg = "#2e3440"
good_bg = "#a3be86"
good_fg = "#2e3440"
warning_bg = "#ebcb8b"
warning_fg = "#2e3440"
critical_bg = "#bf616a"
critical_fg = "#2e3440"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

